# Generated by Django 3.1.3 on 2020-11-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_image_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='instargam',
            new_name='instagram',
        ),
    ]
