# Generated by Django 3.1.3 on 2020-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201107_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
