# Generated by Django 3.1.3 on 2020-11-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_information_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('instagram_post_link', models.URLField()),
            ],
        ),
    ]
